### ISSUE TITLE
Less "ghosting" option

### ISSUE THREAD

**Issue by Troberg** [skipadu/obsidian-ghost-fade-focus#2]
This plugin is great, and the concept is sound, but the ghosting is too extreme, especially when looking at lists of one line items.

It would be nice to have an option for a less extreme version, where the maximum ghosting is about the same level as the second level of ghosting today (the second out from the center line). Maybe also a "highlight current line only" option.

Alternatively, have settings for each level of ghosting, so the user can do it anyway he wants.

**Comment by skipadu** [comment]
Thanks for the enhancement ideas! 

I originally wanted to include configurable opacity levels, but couldn't get it done so I went with the "Minimum Viable Product" mentality.
I try to investigate this in the future and will update this issue accordingly.

**Comment by skipadu** [comment]
@Troberg With the latest [release](https://github.com/skipadu/obsidian-ghost-fade-focus/releases/tag/2.1.0) you should now be able to adjust the opacity levels to your liking.

Currently there is no button to reset the opacity level to default as I couldn't get it working. As a workaround for now, I added the default value to description of each slider.

I hope you like it! ☺️
