### ISSUE TITLE
start obsidian turned off?

### ISSUE THREAD

**Issue by chad-bennett** [skipadu/obsidian-ghost-fade-focus#3]
is it possible to have the default setting to be turned off? i love this for long writing, but don't want it turned on for everything else that i do. would like the option to turn it on myself only when needed.

**Comment by ShadiestGoat** [comment]
Completly agree

**Comment by skipadu** [comment]
I made changes regarding this and it is available in the new [2.0.0 release](https://github.com/skipadu/obsidian-ghost-fade-focus/releases/tag/2.0.0).

Hopefully this makes it nicer to use!
