### ISSUE TITLE
it is not working 

### ISSUE THREAD

**Issue by onqun** [skipadu/obsidian-ghost-fade-focus#7]
Hello, your amazing plugin not working :/. v.0.13.14

**Comment by HuangAdam** [comment]
+1

**Comment by skipadu** [comment]
Thanks for the report!
I confirmed this in `v0.13.24`. Will need to investigate what have changed in Obsidian that this is no longer working.

**Comment by nybbles** [comment]
same here, I just installed it, but it does not work at all.

**Comment by desouzafelipe** [comment]
Same here too. And the plugin looks so nice to read! Using Obsidian v0.13.23 with California Coast Theme.

**Comment by YIRU69** [comment]
same here, I just installed it, but it does not work at all.

**Comment by skipadu** [comment]
Sorry for the plug-in to still be broken.

I have looked this a little and it seems to require full rewrite of the plug-in because Obsidian have changed the underlying CodeMirror 5 to CodeMirror 6. 

Haven’t had enough time for this task as other activities and hobbies have taken all the time available.

I’m planning to get it fixed but not able to say when it’s ready.

**Comment by skipadu** [comment]
I did delve into this and was able to convert it to work with CodeMirror 6.

Currently having some small problem that I try to fix later today. It is not dealbreaker in my opinion, so I'm planning to release on tomorrow with or without the fix. And if the latter; bringing new version later if I manage to fix it.

**Comment by skipadu** [comment]
This issue should be now solved with the recent release, [v3.0.0](https://github.com/skipadu/obsidian-ghost-fade-focus/releases/tag/3.0.0).
Tested it to work with the Obsidian v0.15.9.

**Comment by redactedscribe** [comment]
It appears to work great now, thanks!

**Comment by desouzafelipe** [comment]
It is working fine now! Thanks a lot and congratulations for making this plugin for the community!
